name: Update Site

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    name: Update Site
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repo

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'

    - uses: borales/actions-yarn@v2.3.0
      name: Install Dependencies
      with:
        cmd: install # will run `yarn install` command

    - uses: borales/actions-yarn@v2.3.0
      name: Build Site
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      with:
        cmd: build # will run `yarn build` command

    - name: Publish Site
      uses: cloudflare/wrangler-action@1.2.0
      if: github.ref == 'refs/heads/main'
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
